version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: product_data_pipeline_db
    environment:
      POSTGRES_USER: productuser         
      POSTGRES_PASSWORD: productpassword 
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    volumes:
      - ./app/src/main/resources/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: productdb
      DB_USER: productuser
      DB_PASSWORD: productpassword
    volumes:
      - ./app/src/main/resources/smalldata.csv:/app/src/main/resources/smalldata.csv

volumes:
  postgres_data:
